### ISSUE TITLE
Supervisor SP

### ISSUE THREAD

**Issue by larsbrinkhoff** [e8johan/tosemu#10]
Hello,

The initial value of the supervisor stack pointer is set to 0x600.  However, when switching to supervisor mode and pushing something to the stack, the memory area below 0x600 doesn't exist.

**Comment by e8johan** [comment]
Correct. That is because of the "mmu" that lets you define memory areas with access functions. Below 0x600, every memory address is to be represented by some magical reader function. You can see an example of this here: https://github.com/e8johan/tosemu/blob/master/tossystem.c#L159

**Comment by larsbrinkhoff** [comment]
I tested running a real TOS application: `LHarc`.  Apparently, it runs `Supexec` and expects the initial supervisor stack pointer to be usable.  So I suspect tosemu should set it to a suitable location in RAM.

I tried pointing the SSP to near the end of RAM, and that seemed to fix this problem.

**Comment by e8johan** [comment]
Aha :-)

That could be the case, yes.

On Thu, Jun 16, 2016 at 3:23 PM Lars Brinkhoff <notifications@github.com>
wrote:

> I tested running a real TOS application: LHarc. Apparently, it runs
> Supexec and expects the initial supervisor stack pointer to be usable. So
> I suspect tosemu should set it to a suitable location in RAM.
>
> I tried pointing the SSP to near the end of RAM, and that seemed to fix
> this problem.
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/e8johan/tosemu/issues/10#issuecomment-226483382>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABpw85Tpj7JXye1KWqkVdGvqHKGW0rHUks5qMU5agaJpZM4I3W09>
> .
>
-- 

---
Johan Thelin

Recommended on-line reading:
http://www.thelins.se | http://www.foss-gbg.se
Recommended off-line reading:
The Foundations of Qt Development (ISBN: 1-59059-831-8)

**Comment by larsbrinkhoff** [comment]
Fixed by #11.
