### ISSUE TITLE
Travis April 2020 fails: cant find cross-mint-essential

### ISSUE THREAD

**Issue by paulwratt** [e8johan/tosemu#21]
> E: Unable to locate package cross-mint-essential

I believe this has been fixed (according to commit log), but the Travis build is not working, unless the url has changed again (recently?)

note: there are other `W: Failed` warnings as well

**Comment by paulwratt** [comment]
the "cross-mint" PPA has changed packaging - all `*-m68k-atari-mint`' lib packages are now "arch=all"

BTW the minimal available distro in the PPA is "Xenial"

**Comment by e8johan** [comment]
Fixed this when migrating from Travis CI to github actions.

**Comment by paulwratt** [comment]
:)
