### ISSUE TITLE
Automated tests

### ISSUE THREAD

**Issue by larsbrinkhoff** [e8johan/tosemu#6]
I would like to add some kind of automated tests.

I my idea is to run small TOS programs that signal success or failure through their exit code.  It would be easy to add them as binary executables, but I believe it's important that the source code is present and built automatically.

Does anyone know about some cross assembler (or possibly C toolchain) that targets TOS executables?

**Comment by larsbrinkhoff** [comment]
Maybe this?

https://github.com/vinriviere/m68k-atari-mint-binutils-gdb

**Comment by larsbrinkhoff** [comment]
Sorry, I just now saw that this is already covered in the README.

**Comment by e8johan** [comment]
I guess you noticed the tests directory as well. However, they still need to be automated. Now they are more for manual verification than for preventing regressions.

**Comment by larsbrinkhoff** [comment]
Right!

I now have changes to download and build binutils and gcc for m68k-atari-mint.  Binutils adds five minutes, gcc another fifteen.  Of course, it would be best to have pre-built .debs.

**Comment by e8johan** [comment]
I install them from here: http://vincent.riviere.free.fr/soft/m68k-atari-mint/ubuntu.php

The Ubuntu Wily packages seems to work for Debian Jessie.

**Comment by larsbrinkhoff** [comment]
I tried those, but they didn't work in Trusty due to package conflicts.  Travis CI supports Precise and Trusty.  The page says that only Xenial is supported.

Are you saying there are other packages available?

**Comment by larsbrinkhoff** [comment]
Oh, I see them now!
